Refactor error logging to use f-string format
Change the format as it led to an exception:
> logger.error('** %s - %d %s' % (name, ex, ex))
TypeError: %d format: a real number is required, not BadRequestError